// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type AppUser struct {
	ID        int32
	Name      string
	Email     string
	Password  string
	Birthday  time.Time
	CreatedAt time.Time
}
