// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package database

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
insert into app.user(name, email, password, birthday)
values ($1, $2, $3, $4)
returning id, name, email, password, birthday, created_at
`

type CreateUserParams struct {
	Name     string
	Email    string
	Password string
	Birthday time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Birthday,
	)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Birthday,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserById = `-- name: DeleteUserById :exec
delete from app.user u
where u.id = $1
`

func (q *Queries) DeleteUserById(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUserById, id)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
select id, name, email, password, birthday, created_at from app.user u
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]AppUser, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppUser
	for rows.Next() {
		var i AppUser
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.Birthday,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, name, email, password, birthday, created_at from app.user u
where u.email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Birthday,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, name, email, password, birthday, created_at from app.user u
where u.id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Birthday,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserById = `-- name: UpdateUserById :one
update app.user set
	name = $2,
	email = $3,
	password  = $4,
	birthday = $5
where id = $1
returning id, name, email, password, birthday, created_at
`

type UpdateUserByIdParams struct {
	ID       int32
	Name     string
	Email    string
	Password string
	Birthday time.Time
}

func (q *Queries) UpdateUserById(ctx context.Context, arg UpdateUserByIdParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, updateUserById,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Birthday,
	)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Birthday,
		&i.CreatedAt,
	)
	return i, err
}
